export const CHANGE_SEARCH_INPUT = "ADD_REVENUE"

export const CHANGE_SELECTED_AREA = "CHANGE_SELECTED_AREA"
export const CHANGE_SELECTED_COMPETITION = "CHANGE_SELECTED_COMPETITION"
export const CHANGE_SELECTED_TEAM = "CHANGE_SELECTED_TEAM"
export const CHANGE_SELECTED_PLAYER = "CHANGE_SELECTED_PLAYER"