export const CHANGE_SEARCH_INPUT = "ADD_REVENUE"

export const CHANGE_SELECTED_AREA = "CHANGE_SELECTED_AREA"
export const CHANGE_SELECTED_COMPETITION = "CHANGE_SELECTED_COMPETITION"
export const CHANGE_SELECTED_TEAM = "CHANGE_SELECTED_TEAM"
export const CHANGE_SELECTED_PLAYER = "CHANGE_SELECTED_PLAYER"


export const SET_AREAS = "SET_AREAS"
export const SET_COMPETITIONS = "SET_COMPETITONS"
export const SET_TEAMS = "SET_TEAMS"
export const SET_PLAYERS = "SET_PLAYERS"